# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kate Schmidt
email: Shrumm@wustl.edu
description: > # this means to ignore newlines until "baseurl:"
  Kate Schmidt is a graduate student in the Philosophy, Neuroscience, and Physiology (PNP) program at Washington University in Saint Louis.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kcsschmidt.com" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
